dev
size12/gophkeeper pull request #1
Opened 2023-04-28 17:15 UTC by size12

В целом сделал основной функционал. В планах сделать тесты, чтение конфига из файла, добавить документацию. 
Насчёт тестов вопрос, получается мне нужно сделать тесты только для хендлеров и хранилища? Тесты для терминального интерфейса не надо?

2023-05-01 16:52 UTC, Bazys requested changes

2023-05-01 16:52 UTC, Bazys commented on cmd/server/server.go
> +	select {}
ну это совсем страшный костыль.

2023-05-01 16:52 UTC, Bazys commented on internal/client/tui.go
> +	"github.com/size12/gophkeeper/internal/entity"
ну вот тут не вижу совсем  DI
этот пакет прям знает обо всём

2023-05-01 16:52 UTC, Bazys commented on internal/entity/entity.go
> +const (
посмотри как эмулируются enum в го

2023-05-01 16:52 UTC, Bazys commented on internal/entity/entity.go
> +	ExpirationDate string
а у тебя есть гарантия что пользователь укажет правильную дату? а если укажет через | ?

2023-05-01 16:52 UTC, Bazys commented on internal/handlers/client.go
> +	authToken entity.AuthToken
а если 2 разных пользователя одновременно залогинятся?
может все таки в контексте?

2023-05-01 18:14 UTC, size12 commented on cmd/server/server.go
> +	select {}
ага, в планах было доделать как раз

2023-05-01 18:15 UTC, size12 commented on internal/entity/entity.go
> +	ExpirationDate string
ок, доделаю

2023-05-03 17:12 UTC, size12 commented on internal/handlers/client.go
> +	authToken entity.AuthToken
не может быть такого, для каждого пользователя свой объект предназначен.

2023-05-03 17:13 UTC, size12 commented on internal/entity/entity.go
> +const (
переделал

2023-05-03 17:13 UTC, size12 commented on internal/client/tui.go
> +	"github.com/size12/gophkeeper/internal/entity"
а какие именно должен только видеть?

2023-05-05 14:39 UTC, size12 commented
Ура, я разобрался как мокать интерфейсы, оказалось не сложно :)

2023-05-06 14:25 UTC, merged